const produtos = [
  {
    id: 1,
    nome: "Termômetro Digital",
    preco: "18.84",
    imagem: " ",
    descricao: "Medição rápida e precisa da temperatura.",
    desconto: "15% OFF",
  },
  {
    id: 2,
    nome: "Ibuprofeno 400mg",
    preco: "93.01",
    imagem: " ",
    descricao: "Anti-inflamatório e analgésico.",
    desconto: "10% OFF",
  },
  {
    id: 3,
    nome: "Pomada para Assaduras",
    preco: "78.64",
    imagem: " ",
    descricao: "Previne e trata assaduras em bebês.",
    desconto: "15% OFF",
  },
  {
    id: 4,
    nome: "Shampoo Anticaspa",
    preco: "97.63",
    imagem: " ",
    descricao: "Combate a caspa e fortalece os fios.",
    desconto: "10% OFF",
  },
  {
    id: 5,
    nome: "Álcool em Gel 70%",
    preco: "66.84",
    imagem: " ",
    descricao: "Higienização rápida e eficaz das mãos.",
    desconto: null,
  },
  {
    id: 6,
    nome: "Termômetro Digital",
    preco: "37.53",
    imagem: " ",
    descricao: "Medição rápida e precisa da temperatura.",
    desconto: "15% OFF",
  },
  {
    id: 7,
    nome: "Protetor Solar FPS 50",
    preco: "45.38",
    imagem: " ",
    descricao: "Proteção alta contra raios UVA e UVB.",
    desconto: "15% OFF",
  },
  {
    id: 8,
    nome: "Desodorante Roll-On",
    preco: "35.99",
    imagem: " ",
    descricao: "Proteção contra odores por 48h.",
    desconto: "15% OFF",
  },
  {
    id: 9,
    nome: "Termômetro Digital",
    preco: "25.38",
    imagem: " ",
    descricao: "Medição rápida e precisa da temperatura.",
    desconto: "15% OFF",
  },
  {
    id: 10,
    nome: "Shampoo Anticaspa",
    preco: "98.59",
    imagem: " ",
    descricao: "Combate a caspa e fortalece os fios.",
    desconto: "10% OFF",
  },
  {
    id: 11,
    nome: "Creme Dental Clareador",
    preco: "94.28",
    imagem: " ",
    descricao: "Branqueamento e proteção prolongada.",
    desconto: "20% OFF",
  },
  {
    id: 12,
    nome: "Protetor Solar FPS 50",
    preco: "70.97",
    imagem: " ",
    descricao: "Proteção alta contra raios UVA e UVB.",
    desconto: "10% OFF",
  },
  {
    id: 13,
    nome: "Esparadrapo 10cm x 4,5m",
    preco: "96.74",
    imagem: " ",
    descricao: "Fixação de curativos e dispositivos.",
    desconto: "10% OFF",
  },
  {
    id: 14,
    nome: "Termômetro Digital",
    preco: "22.86",
    imagem: " ",
    descricao: "Medição rápida e precisa da temperatura.",
    desconto: "15% OFF",
  },
  {
    id: 15,
    nome: "Álcool em Gel 70%",
    preco: "86.63",
    imagem: " ",
    descricao: "Higienização rápida e eficaz das mãos.",
    desconto: "15% OFF",
  },
  {
    id: 16,
    nome: "Creme Dental Clareador",
    preco: "39.41",
    imagem: " ",
    descricao: "Branqueamento e proteção prolongada.",
    desconto: "10% OFF",
  },
  {
    id: 17,
    nome: "Creme Dental Clareador",
    preco: "57.23",
    imagem: " ",
    descricao: "Branqueamento e proteção prolongada.",
    desconto: null,
  },
  {
    id: 18,
    nome: "Curativo Adesivo",
    preco: "67.05",
    imagem: " ",
    descricao: "Protege pequenos ferimentos.",
    desconto: "15% OFF",
  },
  {
    id: 19,
    nome: "Shampoo Anticaspa",
    preco: "94.82",
    imagem: " ",
    descricao: "Combate a caspa e fortalece os fios.",
    desconto: null,
  },
  {
    id: 20,
    nome: "Sabonete Líquido Antisséptico",
    preco: "14.28",
    imagem: " ",
    descricao: "Limpeza profunda com proteção antibacteriana.",
    desconto: "10% OFF",
  },
  {
    id: 21,
    nome: "Colágeno Hidrolisado",
    preco: "47.36",
    imagem: " ",
    descricao: "Melhora elasticidade da pele e articulações.",
    desconto: "15% OFF",
  },
  {
    id: 22,
    nome: "Creme Dental Clareador",
    preco: "70.78",
    imagem: " ",
    descricao: "Branqueamento e proteção prolongada.",
    desconto: "20% OFF",
  },
  {
    id: 23,
    nome: "Gaze Estéril 7,5x7,5",
    preco: "83.70",
    imagem: " ",
    descricao: "Absorção de secreções e cobertura de feridas.",
    desconto: "10% OFF",
  },
  {
    id: 24,
    nome: "Vitamina C 1000mg",
    preco: "64.13",
    imagem: " ",
    descricao: "Reforça a imunidade e combate radicais livres.",
    desconto: "20% OFF",
  },
  {
    id: 25,
    nome: "Colágeno Hidrolisado",
    preco: "14.05",
    imagem: " ",
    descricao: "Melhora elasticidade da pele e articulações.",
    desconto: "10% OFF",
  },
  {
    id: 26,
    nome: "Soro Fisiológico 500ml",
    preco: "78.67",
    imagem: " ",
    descricao: "Hidratação e limpeza de mucosas.",
    desconto: "15% OFF",
  },
  {
    id: 27,
    nome: "Luva Cirúrgica Descartável",
    preco: "95.85",
    imagem: " ",
    descricao: "Ideal para procedimentos médicos.",
    desconto: null,
  },
  {
    id: 28,
    nome: "Curativo Adesivo",
    preco: "37.47",
    imagem: " ",
    descricao: "Protege pequenos ferimentos.",
    desconto: null,
  },
  {
    id: 29,
    nome: "Gaze Estéril 7,5x7,5",
    preco: "77.30",
    imagem: " ",
    descricao: "Absorção de secreções e cobertura de feridas.",
    desconto: "10% OFF",
  },
  {
    id: 30,
    nome: "Multivitamínico A-Z",
    preco: "12.70",
    imagem: " ",
    descricao: "Suplemento com vitaminas e minerais essenciais.",
    desconto: "20% OFF",
  },
  {
    id: 31,
    nome: "Vitamina C 1000mg",
    preco: "99.52",
    imagem: " ",
    descricao: "Reforça a imunidade e combate radicais livres.",
    desconto: "15% OFF",
  },
  {
    id: 32,
    nome: "Sabonete Líquido Antisséptico",
    preco: "90.88",
    imagem: " ",
    descricao: "Limpeza profunda com proteção antibacteriana.",
    desconto: null,
  },
  {
    id: 33,
    nome: "Soro Fisiológico 500ml",
    preco: "73.12",
    imagem: " ",
    descricao: "Hidratação e limpeza de mucosas.",
    desconto: "10% OFF",
  },
  {
    id: 34,
    nome: "Paracetamol 500mg",
    preco: "22.20",
    imagem: " ",
    descricao: "Analgésico e antitérmico para dores e febre.",
    desconto: "15% OFF",
  },
  {
    id: 35,
    nome: "Multivitamínico A-Z",
    preco: "69.90",
    imagem: " ",
    descricao: "Suplemento com vitaminas e minerais essenciais.",
    desconto: "15% OFF",
  },
  {
    id: 36,
    nome: "Esparadrapo 10cm x 4,5m",
    preco: "42.29",
    imagem: " ",
    descricao: "Fixação de curativos e dispositivos.",
    desconto: null,
  },
  {
    id: 37,
    nome: "Ômega 3 1000mg",
    preco: "51.66",
    imagem: " ",
    descricao: "Auxilia na saúde cardiovascular.",
    desconto: "20% OFF",
  },
  {
    id: 38,
    nome: "Gaze Estéril 7,5x7,5",
    preco: "91.93",
    imagem: " ",
    descricao: "Absorção de secreções e cobertura de feridas.",
    desconto: "10% OFF",
  },
  {
    id: 39,
    nome: "Creme Dental Clareador",
    preco: "21.07",
    imagem: " ",
    descricao: "Branqueamento e proteção prolongada.",
    desconto: "20% OFF",
  },
  {
    id: 40,
    nome: "Pomada para Assaduras",
    preco: "91.52",
    imagem: " ",
    descricao: "Previne e trata assaduras em bebês.",
    desconto: "15% OFF",
  },
  {
    id: 41,
    nome: "Ibuprofeno 400mg",
    preco: "60.58",
    imagem: " ",
    descricao: "Anti-inflamatório e analgésico.",
    desconto: "15% OFF",
  },
  {
    id: 42,
    nome: "Dipirona Sódica 1g",
    preco: "28.74",
    imagem: " ",
    descricao: "Reduz febre e alivia dores intensas.",
    desconto: "15% OFF",
  },
  {
    id: 43,
    nome: "Sabonete Líquido Antisséptico",
    preco: "88.52",
    imagem: " ",
    descricao: "Limpeza profunda com proteção antibacteriana.",
    desconto: null,
  },
  {
    id: 44,
    nome: "Ômega 3 1000mg",
    preco: "44.84",
    imagem: " ",
    descricao: "Auxilia na saúde cardiovascular.",
    desconto: "15% OFF",
  },
  {
    id: 45,
    nome: "Shampoo Anticaspa",
    preco: "38.65",
    imagem: " ",
    descricao: "Combate a caspa e fortalece os fios.",
    desconto: "15% OFF",
  },
  {
    id: 46,
    nome: "Sabonete Líquido Antisséptico",
    preco: "98.86",
    imagem: " ",
    descricao: "Limpeza profunda com proteção antibacteriana.",
    desconto: null,
  },
  {
    id: 47,
    nome: "Vitamina C 1000mg",
    preco: "82.44",
    imagem: " ",
    descricao: "Reforça a imunidade e combate radicais livres.",
    desconto: "20% OFF",
  },
  {
    id: 48,
    nome: "Soro Fisiológico 500ml",
    preco: "11.39",
    imagem: " ",
    descricao: "Hidratação e limpeza de mucosas.",
    desconto: null,
  },
  {
    id: 49,
    nome: "Soro Fisiológico 500ml",
    preco: "44.40",
    imagem: " ",
    descricao: "Hidratação e limpeza de mucosas.",
    desconto: null,
  },
  {
    id: 50,
    nome: "Colágeno Hidrolisado",
    preco: "46.03",
    imagem: " ",
    descricao: "Melhora elasticidade da pele e articulações.",
    desconto: "15% OFF",
  },
];

export { produtos };